export const EventsData = [
  {
    title: "Массаж при остеохондрозе",
    key: "1",
    date: "17 октября",
    type: "conference",
    cost: "",
    photo: "../../assets/img/slider/events_page_yarik.jpg",
    name: "Ярослав",
    surname: "Селезнев",
    experience: "24 года опыта",
    city: "Москва",
    description: (
      <p>
        Массаж шейного отдела делают в положении лежа на животе на кушетке или в
        специализированном кресле. Для обеспечения комфорта врач применяет
        массажное масло. Процесс состоит из трех этапов для качественной
        проработки мышц, позвоночник трогать нельзя.
      </p>
    ),
  },
  {
    title: "Вебинар по невралгиям",
    key: "2",
    date: "27 сентября",
    type: "webinar",
    cost: "$112",
    photo: "../../assets/img/slider/events_page_anna.jpg",
    name: "Анна",
    surname: "Дорошевич",
    experience: "18 лет опыта",
    city: "Минск",
    description: (
      <p>
        Невралгия может быть как самостоятельным заболеванием, так и признаком
        какого-либо патологического состояния. Обычно она возникает из-за
        сдавления нерва: это происходит из-за неправильной осанки или смещения
        костей. Спровоцировать развитие невралгии могут следующие причины:
        переохлаждение тканей;
      </p>
    ),
  },
  {
    title: "какой-то курс",
    key: "3",
    date: "",
    type: "course",
    cost: "",
    photo: "",
    name: "",
    surname: "",
    experience: "",
    city: "",
    description: <p>Пока без текста</p>,
  },
  {
    title: "еще какой-то курс",
    key: "4",
    date: "",
    type: "course",
    cost: "",
    photo: "",
    name: "",
    surname: "",
    experience: "",
    city: "",
    description: <p>Пока без текста</p>,
  },
  {
    title: "и еще какой-то курс",
    key: "5",
    date: "",
    type: "course",
    cost: "",
    photo: "",
    name: "",
    surname: "",
    experience: "",
    city: "",
    description: <p>Пока без текста</p>,
  },
  {
    title: "в общем пара курсов",
    key: "6",
    date: "",
    type: "course",
    cost: "",
    photo: "",
    name: "",
    surname: "",
    experience: "",
    city: "",
    description: <p>Пока без текста</p>,
  },
  {
    title: "еще одна конференция",
    key: "7",
    date: "",
    type: "conference",
    cost: "",
    photo: "",
    name: "",
    surname: "",
    experience: "",
    city: "",
    description: <p>Пока без текста</p>,
  },
  {
    title: "три хватит думаю",
    key: "8",
    date: "",
    type: "conference",
    cost: "",
    photo: "",
    name: "",
    surname: "",
    experience: "",
    city: "",
    description: <p>Пока без текста</p>,
  },
  {
    title: "хотя ладно еще одну",
    key: "9",
    date: "",
    type: "conference",
    cost: "",
    photo: "",
    name: "",
    surname: "",
    experience: "",
    city: "",
    description: <p>Пока без текста</p>,
  },
  {
    title: "и еще",
    key: "10",
    date: "",
    type: "conference",
    cost: "",
    photo: "",
    name: "",
    surname: "",
    experience: "",
    city: "",
    description: <p>Пока без текста</p>,
  },
  {
    title: "тут тоже парочку нужно сделать",
    key: "11",
    date: "",
    type: "webinar",
    cost: "",
    photo: "",
    name: "",
    surname: "",
    experience: "",
    city: "",
    description: <p>Пока без текста</p>,
  },
  {
    title: "сейчас еще попробую много текста в название накидать",
    key: "12",
    date: "17 октября",
    type: "webinar",
    cost: "",
    photo: "",
    name: "",
    surname: "",
    experience: "",
    city: "",
    description: <p>Пока без текста</p>,
  },
  {
    title: "не знаю что насчёт фоток",
    key: "13",
    date: "",
    type: "webinar",
    cost: "",
    photo: "",
    name: "",
    surname: "",
    experience: "",
    city: "",
    description: <p>Пока без текста</p>,
  },
  {
    title: "места вообще мало так-то",
    key: "14",
    date: "",
    type: "webinar",
    cost: "",
    photo: "",
    name: "",
    surname: "",
    experience: "",
    city: "",
    description: <p>Пока без текста</p>,
  },
  {
    title: "а это всё еще и адаптировать",
    key: "15",
    date: "",
    type: "webinar",
    cost: "",
    photo: "",
    name: "",
    surname: "",
    experience: "",
    city: "",
    description: <p>Пока без текста</p>,
  },
  {
    title: "эх......",
    key: "16",
    date: "",
    type: "webinar",
    cost: "",
    photo: "",
    name: "",
    surname: "",
    experience: "",
    city: "",
    description: <p>Пока без текста</p>,
  },
];
